### ISSUE TITLE
dbupgrade in waent.yml

### ISSUE THREAD

**Issue by Gress34** [WhatsApp/whatsapp-business-api-deployment-templates#6]
Hello everyone.
I have in production whatsapp api client using aws on premises templates. I have encounter an error while trying to update from 2.41.3 to 2.43.1. The mistake is in ECS.
Exit code:-
CannotStartContainerError: Error response from daemon: failed to create shim tas: OCI runtime create failed: runc create failed: unable to start container process: exec: "launch_within_docker.sh": cannot run executable found relative to current directory.

I resolved this by installing manually on EC2 dbupgrade-compose.yml and then execute docker-compose up-d. In that way the update was possible.

My question is how to automate dbupgrade on waent.yml and perform the automation with cloudformation?
Otherwise how can I resolve this problem?
![bug](https://user-images.githubusercontent.com/126826160/222559904-72f95c63-e279-4906-b8d9-605847cf8030.JPG)

**Comment by nemani** [comment]
Hello,
Thanks for reporting this issue. We are working on a fix for this. :)
