### ISSUE TITLE
exec: "launch_within_docker.sh": cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by Jrgels** [WhatsApp/whatsapp-business-api-deployment-templates#7]
Hello everyone.
I have in production whatsapp api client using [the aws archive guide](https://developers.facebook.com/docs/whatsapp/on-premises/get-started/installation/aws-archive) on premises templates. I have encounter an error while trying to update from 2.41.3 to 2.43.1. 

The mistake is in ECS (see the image below):
Exit code:-
CannotStartContainerError: Error response from daemon: failed to create shim tas: OCI runtime create failed: runc create failed: unable to start container process: exec: "launch_within_docker.sh": cannot run executable found relative to current directory.

I resolved this by installing manually on EC2 dbupgrade-compose.yml and then execute docker-compose up-d. In that way the update was possible.

My question is how to automate dbupgrade on waent.yml and perform the automation with cloudformation?
Otherwise how can I resolve this problem?
![error](https://user-images.githubusercontent.com/50886064/222577244-33dbdd38-1064-4d1d-b1b6-0eb6f64b96a0.JPG)

**Comment by nemani** [comment]
Hello,
Thanks for reporting this issue. 
We are working on a fix for this.

**Comment by ffileppo-symphony** [comment]
Hello,

we're facing the same issue when provisioning new Whatsapp Business APIs:

`CannotStartContainerError: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "launch_within_docker.sh": cannot run executable found relative to current directory`

**Comment by nemani** [comment]
Can you try it again with the merged PR ? 
We need to explicitly provide the command to docker run `/opt/whatsapp/bin/launch_with_docker.sh`
@ffileppo-symphony which instructions are you following for your setup?

**Comment by nemani** [comment]
@Jrgels we have added CFN template v2.3.9 to https://wa-biz-cfn.s3.amazonaws.com/wa_ent.yml You may want to use v3.0.1 from this repository.

**Comment by nemani** [comment]
Closing this task as I assume the problems have been fixed. 


## Support for this repo
This GitHub repo is not actively monitored. If you need help, please check previously asked questions in the [WA Business API Developer Community](https://developers.facebook.com/community?sort=trending&category=766772797555412) or raise a [Direct support ticket](https://developers.facebook.com/docs/whatsapp/contact-support). Meanwhile, we are happy to continue with less time-sensitive discussions in GitHub.
